# Site settings
title: Dave Compton
email: davecompton7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  What I am doing, what I have done, and what I learned along the way.
baseurl: "/myBlog" # the subpath of your site, e.g. /blog/
url: "http://dc25.github.io" # the base hostname & protocol for your site

twitter_username: dc1234
github_username:  dc25

# Set this to a github repository to be used to host comments.
# github_comments_repository:  githubId/repositoryName

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
